### PR TITLE
Add BdvFunctions.show overload for VolatileARGBType

### PR DESCRIPTION
**Pull request by hanslovsky**
This is an auxiliary pull request to help merge the two commits in #4 as two separate pull requests.

### CODE REVIEW

**Comment by hanslovsky** [comment]
Can this be merged?

**Comment by tpietzsch** [comment]
@hanslovsky I'm on it

**Comment by tpietzsch** [comment]
@hanslovsky I'm doing it together with merging @igorpisarev PRs and cleaning up. So it may take a little while, but should be done tomorrow

**Comment by hanslovsky** [comment]
Thanks @tpietzsch It makes a lot of sense to combine those two PRs!

**Pull request merged**
