### PR TITLE
Add BdvFunctions.show overload for RandomAccessible

### PR DESCRIPTION
**Pull request by hanslovsky**
I c&p'ed and modified as needed. It worked for my classification tool. If there are no caveats, this should be ready to merge.

Update: Originally, this PR contained only a single commit. I accidently commited a second commit in the same branch. Still, we would like to merge the two commits in two separate pull requests. I created #5 so we can merge b03f7d2 first. Once #5 is merged, this PR will contain only a single commit efcc7d6.

### CODE REVIEW

**Comment by hanslovsky** [comment]
I accidentally pushed another commit to this branch but this might as well be part of this pull request. Let me know if you'd rather split it up into two separate PRs.

**Comment by tpietzsch** [comment]
@hanslovsky yes, could you split it please?

**Comment by hanslovsky** [comment]
I will do that, maybe by the end of the week, or next week.

**Comment by hanslovsky** [comment]
Once #5 is merged, this can be merged as well. That way, the two commits in this PR will be merged in two separate pull requests.

**Comment by tpietzsch** [comment]
This was addressed as part of #8

**Pull request closed without merging**
