### PR TITLE
Merges

### PR DESCRIPTION
**Pull request by tpietzsch**
@igorpisarev @hanslovsky @axtimwalde I merged all open PRs into this one. I refactored and cleaned up A LOT. Could you please verify that everything still works in your use cases? After that I'll merge and release...

### CODE REVIEW

**Comment by igorpisarev** [comment]
Works for me.
Thanks @tpietzsch, looks great and much cleaner now :)

**Comment by hanslovsky** [comment]
I will check it out and test it right away. Great work, much appreciated @tpietzsch

**Comment by hanslovsky** [comment]
These lines don't compile anymore:
https://github.com/hanslovsky/imglib2-atlas/blob/master/src/main/java/net/imglib2/atlas/PaintLabelsAndTrain.java#L256
https://github.com/hanslovsky/imglib2-atlas/blob/master/src/main/java/net/imglib2/atlas/PaintLabelsAndTrain.java#L261
I will figure out why and update my code, and post the solution.

**Comment by tpietzsch** [comment]
@hanslovsky `VF extends NumericType< VF >` is now required probably

**Comment by hanslovsky** [comment]
@tpietzsch Yes, that was basically it: hanslovsky/imglib2-atlas@78770ee
I just had to change
```java
VF extends Volatile< F > >
```
to
```java
VF extends AbstractVolatileRealType< F, VF > >
```

**Comment by tpietzsch** [comment]
Thanks guys! I merged this and released 1.0.0-beta-6

**Pull request merged**
